package com.openGG.psymed.plattform.Medical_Management.medic_sections.domain.model.entities;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

/**
 * Entity representing a medical section related to a patient.
 * A section may include information such as a diagnosis, therapy notes, or observations.
 */

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Section {

    /**
     * Unique identifier for the section.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Identifier of the patient associated with this section.
     */
    private Long patientId;

    /**
     * Type of the section (e.g., diagnosis, therapy, note).
     */
    private String type;

    /**
     * Content or detailed information of the section.
     */
    private String content;

    /**
     * Date the section was created.
     */
    private LocalDate createdAt;
}